server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:transactiondb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    database: H2
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true