server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:transactiondb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true