server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: never
